- name: "添加mysql环境变量"
  lineinfile:
    path: /etc/profile
    line: |
      export MYSQL_HOME={{ mysql_install_path }}/mysql
      export PATH=$MYSQL_HOME/bin:$PATH
    state: present

- name: "加载环境变量"
  shell: source /etc/profile
  changed_when: false